// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iucs.pharmacy.domain.Data;

#nullable disable

namespace iucs.pharmacy.domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213043311_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("text")
                        .HasColumnName("customer_code");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Mobile")
                        .HasColumnType("text")
                        .HasColumnName("mobile");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturer_name");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.HasKey("Id")
                        .HasName("pk_manufacturer");

                    b.ToTable("manufacturer");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DefaultGstPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("default_gst_percent");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dosage_form");

                    b.Property<string>("GenericName")
                        .HasColumnType("text")
                        .HasColumnName("generic_name");

                    b.Property<string>("HsnCode")
                        .HasColumnType("text")
                        .HasColumnName("hsn_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsControlled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_controlled");

                    b.Property<bool>("IsPrescriptionRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_prescription_required");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("MedicineCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medicine_code");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medicine_name");

                    b.Property<string>("PackSize")
                        .HasColumnType("text")
                        .HasColumnName("pack_size");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_type");

                    b.Property<string>("Strength")
                        .HasColumnType("text")
                        .HasColumnName("strength");

                    b.HasKey("Id")
                        .HasName("pk_medicine");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_medicine_category_id");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_medicine_manufacturer_id");

                    b.ToTable("medicine");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.MedicineCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_medicine_category");

                    b.ToTable("medicine_category");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_name");

                    b.Property<string>("DoctorRegistrationNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_registration_no");

                    b.Property<string>("HospitalName")
                        .HasColumnType("text")
                        .HasColumnName("hospital_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("PrescriptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prescription_date");

                    b.Property<string>("PrescriptionImagePath")
                        .HasColumnType("text")
                        .HasColumnName("prescription_image_path");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_prescription");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_prescription_customer_id");

                    b.ToTable("prescription");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Dosage")
                        .HasColumnType("text")
                        .HasColumnName("dosage");

                    b.Property<string>("Duration")
                        .HasColumnType("text")
                        .HasColumnName("duration");

                    b.Property<string>("Frequency")
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<decimal>("QuantityPrescribed")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_prescribed");

                    b.HasKey("Id")
                        .HasName("pk_prescription_item");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("ix_prescription_item_medicine_id");

                    b.HasIndex("PrescriptionId")
                        .HasDatabaseName("ix_prescription_item_prescription_id");

                    b.ToTable("prescription_item");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<string>("DrugLicenseNo")
                        .HasColumnType("text")
                        .HasColumnName("drug_license_no");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Gstin")
                        .HasColumnType("text")
                        .HasColumnName("gstin");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_code");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_name");

                    b.HasKey("Id")
                        .HasName("pk_supplier");

                    b.ToTable("supplier");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasColumnName("alert_type");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.HasKey("Id")
                        .HasName("pk_alert");

                    b.ToTable("alert");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.ControlledDrugRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_name");

                    b.Property<string>("DoctorRegistrationNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_registration_no");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_invoice_id");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_controlled_drug_register");

                    b.ToTable("controlled_drug_register");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.PurchaseInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_no");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("net_amount");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_date");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("numeric")
                        .HasColumnName("total_tax");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_purchase_invoice");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_invoice_supplier_id");

                    b.ToTable("purchase_invoice");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.PurchaseInvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch_no");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<decimal?>("FreeQty")
                        .HasColumnType("numeric")
                        .HasColumnName("free_qty");

                    b.Property<decimal>("GstPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("gst_percent");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("line_total");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("manufacture_date");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<decimal>("Mrp")
                        .HasColumnType("numeric")
                        .HasColumnName("mrp");

                    b.Property<Guid>("PurchaseInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_invoice_id");

                    b.Property<decimal>("PurchaseRate")
                        .HasColumnType("numeric")
                        .HasColumnName("purchase_rate");

                    b.Property<decimal>("ReceivedQty")
                        .HasColumnType("numeric")
                        .HasColumnName("received_qty");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("selling_price");

                    b.HasKey("Id")
                        .HasName("pk_purchase_invoice_item");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("ix_purchase_invoice_item_medicine_id");

                    b.HasIndex("PurchaseInvoiceId")
                        .HasDatabaseName("ix_purchase_invoice_item_purchase_invoice_id");

                    b.ToTable("purchase_invoice_item");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_no");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_order_supplier_id");

                    b.ToTable("purchase_order");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("FreeQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("free_quantity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("ordered_quantity");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_item");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("ix_purchase_order_item_medicine_id");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_purchase_order_item_purchase_order_id");

                    b.ToTable("purchase_order_item");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_no");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("net_amount");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_discount");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("numeric")
                        .HasColumnName("total_tax");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_invoice_customer_id");

                    b.HasIndex("PrescriptionId")
                        .HasDatabaseName("ix_sales_invoice_prescription_id");

                    b.ToTable("sales_invoice");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesInvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("GstPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("gst_percent");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("line_total");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<decimal>("Mrp")
                        .HasColumnType("numeric")
                        .HasColumnName("mrp");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_invoice_id");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("selling_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice_item");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_sales_invoice_item_batch_id");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("ix_sales_invoice_item_medicine_id");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_sales_invoice_item_sales_invoice_id");

                    b.ToTable("sales_invoice_item");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("integer")
                        .HasColumnName("payment_mode");

                    b.Property<Guid?>("ReceivedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("received_by");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text")
                        .HasColumnName("reference_no");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_invoice_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sales_payment");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_sales_payment_sales_invoice_id");

                    b.ToTable("sales_payment");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("return_date");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_invoice_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sales_return");

                    b.ToTable("sales_return");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesReturnItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("refund_amount");

                    b.Property<Guid>("SalesReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_return_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_return_item");

                    b.HasIndex("SalesReturnId")
                        .HasDatabaseName("ix_sales_return_item_sales_return_id");

                    b.ToTable("sales_return_item");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adjustment_date");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stock_adjustment");

                    b.ToTable("stock_adjustment");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockAdjustmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<decimal>("DifferenceQty")
                        .HasColumnType("numeric")
                        .HasColumnName("difference_qty");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<decimal>("PhysicalQty")
                        .HasColumnType("numeric")
                        .HasColumnName("physical_qty");

                    b.Property<Guid>("StockAdjustmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_adjustment_id");

                    b.Property<decimal>("SystemQty")
                        .HasColumnType("numeric")
                        .HasColumnName("system_qty");

                    b.HasKey("Id")
                        .HasName("pk_stock_adjustment_item");

                    b.HasIndex("StockAdjustmentId")
                        .HasDatabaseName("ix_stock_adjustment_item_stock_adjustment_id");

                    b.ToTable("stock_adjustment_item");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch_no");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CreatedFromPurchaseItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_from_purchase_item_id");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("current_quantity");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<decimal>("GstPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("gst_percent");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("manufacture_date");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<decimal>("Mrp")
                        .HasColumnType("numeric")
                        .HasColumnName("mrp");

                    b.Property<decimal>("OpeningQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("opening_quantity");

                    b.Property<decimal>("PurchaseRate")
                        .HasColumnType("numeric")
                        .HasColumnName("purchase_rate");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("selling_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stock_batch");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("ix_stock_batch_medicine_id");

                    b.ToTable("stock_batch");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockDamageExpiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stock_damage_expiry");

                    b.ToTable("stock_damage_expiry");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_after");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<decimal?>("QuantityIn")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_in");

                    b.Property<decimal?>("QuantityOut")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_out");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceTable")
                        .HasColumnType("text")
                        .HasColumnName("reference_table");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stock_ledger");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_stock_ledger_batch_id");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("ix_stock_ledger_medicine_id");

                    b.ToTable("stock_ledger");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("FromBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_branch_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("ToBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_branch_id");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transfer_date");

                    b.Property<string>("TransferNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transfer_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stock_transfer");

                    b.ToTable("stock_transfer");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockTransferItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid>("StockTransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_transfer_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_transfer_item");

                    b.HasIndex("StockTransferId")
                        .HasDatabaseName("ix_stock_transfer_item_stock_transfer_id");

                    b.ToTable("stock_transfer_item");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.Medicine", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.MedicineCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medicine_medicine_category_category_id");

                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medicine_manufacturer_manufacturer_id");

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.Prescription", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prescription_customer_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.PrescriptionItem", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prescription_item_medicine_medicine_id");

                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prescription_item_prescription_prescription_id");

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.PurchaseInvoice", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_invoice_supplier_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.PurchaseInvoiceItem", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_invoice_item_medicine_medicine_id");

                    b.HasOne("iucs.pharmacy.domain.Entities.Transaction.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_invoice_item_purchase_invoice_purchase_invoice_id");

                    b.Navigation("Medicine");

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.PurchaseOrder", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_supplier_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.PurchaseOrderItem", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_item_medicine_medicine_id");

                    b.HasOne("iucs.pharmacy.domain.Entities.Transaction.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_item_purchase_order_purchase_order_id");

                    b.Navigation("Medicine");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesInvoice", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_sales_invoice_customer_customer_id");

                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .HasConstraintName("fk_sales_invoice_prescription_prescription_id");

                    b.Navigation("Customer");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesInvoiceItem", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Transaction.StockBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_item_stock_batch_batch_id");

                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_item_medicine_medicine_id");

                    b.HasOne("iucs.pharmacy.domain.Entities.Transaction.SalesInvoice", "SalesInvoice")
                        .WithMany("Items")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_item_sales_invoice_sales_invoice_id");

                    b.Navigation("Batch");

                    b.Navigation("Medicine");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesPayment", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Transaction.SalesInvoice", "SalesInvoice")
                        .WithMany()
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_payment_sales_invoice_sales_invoice_id");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesReturnItem", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Transaction.SalesReturn", null)
                        .WithMany("Items")
                        .HasForeignKey("SalesReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_return_item_sales_return_sales_return_id");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockAdjustmentItem", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Transaction.StockAdjustment", null)
                        .WithMany("Items")
                        .HasForeignKey("StockAdjustmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_adjustment_item_stock_adjustment_stock_adjustment_id");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockBatch", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_batch_medicine_medicine_id");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockLedger", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Transaction.StockBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_ledger_stock_batch_batch_id");

                    b.HasOne("iucs.pharmacy.domain.Entities.Masters.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_ledger_medicine_medicine_id");

                    b.Navigation("Batch");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockTransferItem", b =>
                {
                    b.HasOne("iucs.pharmacy.domain.Entities.Transaction.StockTransfer", null)
                        .WithMany("Items")
                        .HasForeignKey("StockTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_transfer_item_stock_transfer_stock_transfer_id");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Masters.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.PurchaseInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.SalesReturn", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockAdjustment", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("iucs.pharmacy.domain.Entities.Transaction.StockTransfer", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
